# .github/workflows/auto-merge.yml
name: Auto Merge Workflow

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  checks: read
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.head_ref == 'auto_versionup' && github.base_ref == 'develop'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # - name: Wait for CI checks
      #   uses: lewagon/wait-on-check-action@v1.3.1
      #   with:
      #     ref: ${{ github.event.pull_request.head.sha }}
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     wait-interval: 30
      #     running-workflow-name: "Auto Merge Workflow"
      #     check-regexp: ".*-task$"
      #     allowed-conclusions: success,skipped

      # - name: Auto merge PR
      #   if: success()
      #   run: |
      #     PR_NUMBER=${{ github.event.pull_request.number }}
          
      #     echo "Merging PR #$PR_NUMBER from auto_versionup to develop"
      #     gh pr merge $PR_NUMBER --squash --delete-branch=false --subject "Auto merge for auto_versionup"
          
      #     if [ $? -eq 0 ]; then
      #       echo "PR #$PR_NUMBER successfully merged"
      #     else
      #       echo "Failed to merge PR #$PR_NUMBER"
      #       exit 1
      #     fi
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
