# .github/workflows/auto-merge.yml
name: Auto Merge Workflow

on:
  pull_request_target:  # 変更点
    types:
      - opened
      - synchronize
      - reopened

permissions:
  checks: read
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: (github.head_ref == 'auto_versionup' && github.base_ref == 'develop') || (github.head_ref == 'develop' && github.base_ref == 'release')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:  # 追加
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Wait for CI checks
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          running-workflow-name: "Auto Merge Workflow"
          check-regexp: ".*-task$"

      - name: Auto merge
        if: success()
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Auto merge for auto_versionup"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"