# .github/workflows/dummy-ci.yml
name: Dummy CI

on:
  pull_request_target:  # 変更点
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: test-task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 追加
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Run Tests
        run: |
          echo "Running tests..."
          sleep 10
          echo "Tests completed successfully!"
        
  build:
    name: build-task
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository  # 追加
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Build
        run: |
          echo "Running build..."
          sleep 10
          echo "Build completed successfully!"